### ISSUE TITLE
In Linear Programming IRL, what are t and u?

### ISSUE THREAD

**Issue by Shaz-5** [neka-nat/inv_rl#3]
In `lp_irl.py`, in the function `lp_irl`, can you please explain this part:

```
    A_ub = np.bmat([[T_stack, I_stack, zero_stack],    # -TR <= t
                    [T_stack, zero_stack, zero_stack], # -TR <= 0
                    [-eye_ss, zero_ss, -eye_ss],  # -R <= u
                    [eye_ss, zero_ss, -eye_ss],   # R <= u
                    [-eye_ss, zero_ss, zero_ss],  # -R <= Rmax
                    [eye_ss, zero_ss, zero_ss]])  # R <= Rmax
    b = np.vstack([np.zeros((n_states * (n_actions-1) * 2 + 2 * n_states, 1)),
                   Rmax * np.ones((2 * n_states, 1))])
```

I don't understand the comments of A_ub and what each of those mean. Could you please explain `A_ub` and `b` and how they relate to the algorithm formulation from the paper? Thanks.

**Comment by neka-nat** [comment]
It is a matrix transformation of the constraints necessary for the algorithm to be solved by linear programming.

**Comment by Shaz-5** [comment]
Thank you. I understand that but I was wondering what each of the matrices mean. For example I understand that the last two matrices : `[-eye_ss, zero_ss, zero_ss]` and `[eye_ss, zero_ss, zero_ss]` are for the condition $|Ri| < Rmax$. 

I would like to know about the other matrices in A_ub if it is possible. Like, what does this mean: `-TR <= t` and `-R <= u`. In these what are `t` and `u`. 

What I understood was that `[T_stack, I_stack, zero_stack]` is for $(P_{a1}(i) - P_a(i) * (I - gamma * P_a1)^{-1} * R) - \lambda||R||_1$ and `[T_stack, zero_stack, zero_stack]` is for $(Pa_1 - Pa) * (I - gamma * Pa_1)^-1 * R >= 0$. Is this correct?

I am just trying to connect this to the algorithm formulation.

**Comment by neka-nat** [comment]
So t and u are slack variables.
The optimization problem, reformulated using t and u, is as follows:

```math
\begin{equation}
\begin{split}
maximize:& \sum_{i \in S} \bigl\{ t_i - \lambda u_i \bigr\} \\
subject:& \bigl(P_{a_1}(i) - P_a(i) \bigr) {\bigl(I - \gamma P_{a_1}(i) \bigr)}^{-1} R \geq t_i \\
& \bigl(P_{a_1}(i) - P_a(i) \bigr) {\bigl(I - \gamma P_{a_1}(i) \bigr)}^{-1} R \geq 0 \\
& -u \leq R \leq u \\
& |R_i| \leq R_{max}
\end{split}
\end{equation}
```

**Comment by Shaz-5** [comment]
Thank you very much for your quick responses!
